apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-cert #${PIHOLE_CERT_NAME}
  namespace: pihole
spec:
  secretName: ${PIHOLE_SECRET_NAME}
  issuerRef:
    name: cert-issuer #${CERT_MANAGER_NAME}
    kind: ClusterIssuer
  commonName: ${URL_PIHOLE}
  dnsNames:
  - ${URL_PIHOLE}