---
- name: Prepare Kubernetes Nodes
  hosts: controlplanes:workers
  become: yes

  tasks:
    - name: Load necessary kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - br_netfilter
        - overlay

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Kubernetes signing key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install containerd
      apt:
        name: containerd
        state: latest

    - name: Configure containerd for Kubernetes
      block:
        - name: Create containerd configuration directory
          file:
            path: /etc/containerd
            state: directory

        - name: Generate and modify containerd configuration for Kubernetes
          shell: |
            containerd config default | sed -e 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml

        - name: Restart containerd
          systemd:
            name: containerd
            state: restarted
            daemon_reload: yes

    - name: Disable swap if enabled
      block:
        - name: Turn off swap
          command: swapoff -a
          when: ansible_swaptotal_mb > 0

        - name: Remove swap from /etc/fstab
          lineinfile:
            path: /etc/fstab
            regexp: '^\s*[^#]\s*swap\s'
            line: "# Commented out by Ansible"
            state: present

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    - name: Hold kubeadm, kubelet, kubectl at their current version
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
        reload: yes

- name: Initialize Kubernetes Master
  hosts: controlplanes
  become: yes

  tasks:
    - name: Check if Kubernetes is already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: admin_conf_check

    - name: Initialize the Kubernetes cluster
      command: kubeadm init --pod-network-cidr=10.0.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf
      when: not admin_conf_check.stat.exists

    - name: Setup kubeconfig for local user
      block:
        - name: Create .kube directory for local user
          file:
            path: "/home/dario/.kube"
            state: directory
            mode: '0755'
            owner: dario
            group: dario

        - name: Copy admin.conf to user's kube config
          copy:
            src: /etc/kubernetes/admin.conf
            dest: "/home/dario/.kube/config"
            remote_src: yes
            owner: dario
            group: dario
      when: admin_conf_check.stat.exists

- name: Install Calico network plugin
  hosts: controlplanes
  become: yes
  tasks:
    - name: Check if Calico is installed
      shell: kubectl get daemonset calico-node --namespace=kube-system
      register: calico_check
      failed_when: calico_check.rc not in [0, 1]
      changed_when: false
      environment:
        KUBECONFIG: "/home/dario/.kube/config"

    - name: Apply Calico Network Plugin
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      when: '"calico-node" not in calico_check.stdout'
      environment:
        KUBECONFIG: "/home/dario/.kube/config"

- name: Get join command
  hosts: controlplanes
  become: yes
  tasks:
    - name: Check if the API server is ready
      uri:
        url: https://192.168.1.10:6443/healthz
        validate_certs: no
      register: api_server_check
      until: api_server_check.status == 200
      retries: 5
      delay: 10

    - name: Print Environment Variables
      command: env
      register: print_env
      changed_when: false
      environment:
        KUBECONFIG: "/home/dario/.kube/config"

    - name: Create token and get join command with verbosity and extended timeout
      shell: timeout 180 kubeadm token create --print-join-command --v=5
      register: join_command
      when: api_server_check is defined and api_server_check.status == 200
      environment:
        KUBECONFIG: "/home/dario/.kube/config"

    - name: Set join command as a fact
      set_fact:
        k8s_join_command: "{{ join_command.stdout }}"
      when: join_command.stdout is defined and join_command.stdout != ''

- name: Join Kubernetes Workers
  hosts: workers
  become: yes
  tasks:
    - name: Join cluster
      shell: "{{ hostvars['192.168.1.10'].k8s_join_command }}"
      register: join_result
      environment:
        KUBECONFIG: "/home/dario/.kube/config"

    - name: Verify successful join
      shell: kubectl get nodes --kubeconfig /home/dario/.kube/config
      register: node_check
      delegate_to: "192.168.1.10"
      retries: 5
      delay: 10
      until: inventory_hostname in node_check.stdout and 'Ready' in node_check.stdout
      failed_when: node_check.rc != 0
      environment:
        KUBECONFIG: "/home/dario/.kube/config"
