---
- name: Get Kubernetes client version
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Check if kubectl is installed
      command: kubectl version --client --output=json
      register: kubectl_installed
      failed_when: false
      changed_when: false

    - name: Set Kubernetes client version as a fact
      set_fact:
        kubernetes_client_version: "{{ (kubectl_installed.stdout | from_json)['clientVersion']['gitVersion'] }}"
      when: kubectl_installed.rc == 0

- name: Install or update kubectl on the workstation
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Download kubectl
      when: kubectl_installed.rc != 0 or kubectl_installed.stdout | from_json | json_query('clientVersion.gitVersion') != kubernetes_client_version
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_client_version }}/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'

    - name: Verify kubectl installation
      command: kubectl version --client

- name: Fetch Kubernetes Configuration to Workstation
  hosts: controlplanes
  gather_facts: no
  tasks:
    - name: Check if admin.conf exists on control plane
      stat:
        path: /etc/kubernetes/admin.conf
      register: admin_conf_check

    - name: Fetch admin.conf to local workstation
      when: admin_conf_check.stat.exists
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "/home/dario/.kube/config"
        flat: yes
      become: yes

- name: Setup kubeconfig on local workstation
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create .kube directory on workstation
      file:
        path: "/home/dario/.kube"
        state: directory
        mode: '0755'

    - name: Copy admin.conf to workstation's kube config
      copy:
        src: "/home/dario/.kube/config"
        dest: "/home/dario/.kube/config"
        remote_src: yes
        mode: '0600'
