---
- name: Copy .tfstate files to control plane node
  hosts: localhost
  gather_facts: no
  vars:
    local_source_dir: "~/cube"
    remote_dest_dir: "~/remote_tfstate_files"  # Adjust as needed for the remote directory on controlplane node
    controlplane_host: "your_controlplane_host"  # Specify your control plane host or group

  tasks:
    - name: Find .tfstate files in the source directory
      find:
        paths: "{{ local_source_dir }}"
        patterns: "*.tfstate"
        recurse: yes
      register: tfstate_files

    - name: Ensure remote directory exists on control plane node
      ansible.builtin.file:
        path: "{{ remote_dest_dir }}"
        state: directory
        mode: '0755'
      delegate_to: "{{ controlplane_host }}"
      become: yes  # Use become as needed based on your controlplane host's requirements

    - name: Copy .tfstate files from workstation to control plane node
      copy:
        src: "{{ item.path }}"
        dest: "{{ remote_dest_dir }}/{{ item.path | regex_replace('^' + local_source_dir + '/', '') }}"
        mode: '0644'
      loop: "{{ tfstate_files.files }}"
      when: tfstate_files.matched > 0
      delegate_to: "{{ controlplane_host }}"
      become: yes  # Use become as needed based on your controlplane host's requirements
