---
- name: Reboot Hosts
  hosts: all
  become: yes

  tasks:
    - name: Reboot the host
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime

    - name: Wait for the host to become reachable again
      wait_for_connection:
        delay: 5
        timeout: 300
