---
- name: Ensure correct permissions and ownership for synchronization directories
  hosts: controlplanes
  gather_facts: no
  become: true
  vars:
    base_remote_dir: "~/cube"  # Define variable here to make it accessible in this play
  tasks:
    - name: Ensure base directory exists and has correct permissions on the remote hosts
      file:
        path: "{{ base_remote_dir }}"
        state: directory
        owner: dario
        group: sudo
        mode: '2775'

- name: Synchronize .tfstate and .tfvars files within ~/cube directory in both directions
  hosts: controlplanes
  gather_facts: no
  vars:
    local_source_dir: "~/cube"
    base_remote_dir: "~/cube"
  tasks:
    - name: Find .tfstate and .tfvars files in the local source directory
      find:
        paths: "{{ local_source_dir }}"
        patterns: "*.tfstate,*.tfvars"
        recurse: yes
      register: found_files
      delegate_to: localhost

    - name: Ensure the base directory exists on the remote hosts
      ansible.builtin.file:
        path: "{{ item.path | regex_replace(local_source_dir, base_remote_dir) | regex_replace('/[^/]+$', '') }}"
        state: directory
        mode: '2775'
        owner: dario
        group: sudo
      loop: "{{ found_files.files }}"
      become: true
      when: found_files.matched > 0

    - name: Synchronize the newest .tfstate and .tfvars files to the remote hosts
      synchronize:
        src: "{{ item.path }}"
        dest: "{{ item.path | regex_replace('^' + local_source_dir, base_remote_dir) }}"
        mode: push
        rsync_opts:
          - "--update"
          - "--times"
          - "--chown=dario:sudo"
          - "--chmod=2775"
      loop: "{{ found_files.files }}"
      when: found_files.matched > 0
      delegate_to: localhost

    - name: Synchronize the newest .tfstate and .tfvars files from the remote hosts to the local directory
      synchronize:
        src: "{{ base_remote_dir }}/"
        dest: "{{ local_source_dir }}/"
        mode: pull
        rsync_opts:
          - "--update"
          - "--times"
          - "--chown=dario:sudo"
          - "--chmod=2775"
      delegate_to: localhost
      become: false
