apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openebs-jiva-csi-node
  namespace: openebs
spec:
  selector:
    matchLabels:
      name: openebs-jiva-csi-node
  template:
    metadata:
      labels:
        name: openebs-jiva-csi-node
    spec:
      hostPID: true
