apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${PIHOLE_CERT_NAME}
  namespace: pihole
spec:
  secretName: ${PIHOLE_SECRET_NAME}
  issuerRef:
    name: ca-issuer #${CERT_MANAGER_NAME}
    kind: ClusterIssuer
  commonName: ${URL_PIHOLE}
  dnsNames:
  - ${URL_PIHOLE}