apiVersion: v1
kind: Namespace
metadata:
  name: pihole
  labels:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  loadBalancerIP: 192.168.1.131
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: pihole
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ports:
    - name: web-tcp-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: web-tcp-https
      protocol: TCP
      port: 443
      targetPort: 443
  loadBalancerIP: 192.168.1.132

